debug: true

server:
    port: 9999

logging:
  level:
    root: INFO

spring:
  freemarker:
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**
  datasource:
    schema: classpath:db/h2_schema.sql
    data: classpath:db/h2_data.sql
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
      enabled: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: "${SPRING_BUS_KAFKA_BROKER_LIST}"
          zkNodes: "${SPRING_BUS_ZK_NODE_LIST}"
    bus:
      trace:
        enabled: true

fehash:
  value: xx99999xxx
  url: 22xxxx222http://fe.iodsp.org
